$LOAD_PATH << File.join(File.dirname(__FILE__), '..')

require 'rspec'
require 'rack/test'
require 'lib/timetastic'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus => true

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.include Rack::Test::Methods
end

# def notify(domain, direction)
#   f = {
#     :hours => 'day',
#     :weeks => 'month',
#     :days =>  'month',
#     :months => 'year'
#   }

#   location  = direction > 0 ? 'last' : 'first'
#   target    = direction > 0 ? 'next' : 'last'
#   reason = "it is the #{location} #{domain[0..-2]} of the #{f[domain]}, can not locate the #{target} one"

#   puts "WARNING: spec skipped because #{reason}"
# end